### ISSUE TITLE
Will not compile using board Version 2.5.0

### ISSUE THREAD

**Issue by git360t** [gpepe/esp8266-sendemail#2]
Currently this sketch works with esp8266 board Version 2.4.2

It will not compile using board Version 2.5.0
Error compiling for board NodeMCU 1.0 (ESP-12E Module)
The compiler error points to line 45 in sendemail.cpp library file
C:\Utilities\arduino-1.8.8\portable\sketchbook\libraries\esp8266-sendemail-master\sendemail.cpp:45:10: error: ambiguous overload for 'operator+=' (operand types are 'String' and 'IPAddress')
buffer += client->localIP();

**Comment by inc90** [comment]
I was able to correct this error by changing one line in `sendemail.cpp`
```
....
buffer = F("EHLO ");
buffer += client->localIP();
```
to
```
....
buffer = F("EHLO ");
buffer += client->localIP().toString();
```

**Comment by detamend** [comment]
Thanks, @inc90 !
